### ISSUE TITLE
Can't connect to the app

### ISSUE THREAD

**Issue by sherman** [aragozin/jvm-tools#11]
Java: 1.8.0_60-b27
App: tomcat-based single webapp under jsvc

sudo java -jar ~/bin/sjk.jar ttop -p 21787 -n 20 -o CPU

The actual result: 
Failed to access MBean server: 21787

**Comment by sherman** [comment]
But with a socket it works.

**Comment by aragozin** [comment]
Java attach is working though files created in default temp directory. If tomcat process is using different temp directory, it would be invisible. If you have -Djava.io.tmpdir option for your tomcat, try to use same option for SJK.
BTW 
Does sjk jps show your tomcat process?
