### ISSUE TITLE
Mistake on documentation page

### ISSUE THREAD

**Issue by alexbudarov** [aragozin/jvm-tools#14]
https://github.com/aragozin/jvm-tools/blob/master/sjk-core/COMMANDS.md#stcap-command

> stcap commands dumps threads from target process with configured period (or non-stop) to a file
> 
>  java -jar sjk.jar mx -p 6344 -mg -b java.lang:type=Memory -f HeapMemoryUsage
> 
> [Stack Capture] Dumps stack traces to file for further processing
> Usage: stcap [options]

Command line example should be something like "java -jar sjk.jar stcap -o ... -p ...", right?

**Comment by aragozin** [comment]
You are right. Fixed that.
