### ISSUE TITLE
Editable JMX connection string

### ISSUE THREAD

**Issue by kyxap1** [aragozin/jvm-tools#15]
Hello, Alexey.

I have a topic to discuss and JMX connection string customization is a subject.

Recent applications servers, for instance Wildfly, offers JMX connection over http-remoting-jmx.
As **jvm-tools** has RMI hard coded in the connection string at JmxConnectionInfo.java, a code change has to be made in order to change the connection type.

I need to know your opinion as for customization of a protocol string, mostly designing related question.
`final String uri = "service:jmx:rmi:///jndi/rmi://" + host + ":" + port + "/jmxrmi";`

Have I to implement customization in one of the preferable ways while using `-cp` with provider's protocol realization:

- Override `service:jmx:rmi:///jndi/rmi://` with my own hardcoded string `service:jmx:remoting-jmx:///jndi/rmi://` while always using WildFly http-jmx interface?
- Allow for override of JMX protocol string with the property setting via `-D` flag?
- Use -s flag value as fully overriding JMX connection string?
- Add new flag to have a chance to form own JMX connection string?

Please, let me know if I need to issue a pull request.
Thank you for your job!

**Comment by aragozin** [comment]
Hi,

How this http-remoting-jmx looks like? Can you used JConsole/JVisualVM to connect via HTTP?
As of options I would enhance -s to accept URI if provided.

**Comment by kyxap1** [comment]
There is an documentation with connector example code:
https://docs.jboss.org/author/display/WFLY8/JMX+subsystem+configuration

Not sure if possible to avoid classpath definition by adding [remoting-jmx](https://github.com/jbossas/remoting-jmx) as maven dependency, but looks like much more straightfoward.

**Comment by aragozin** [comment]
Well,
1. this is proprietary JBoss protocol
2. remoting-jmx requires Java 7 while SJK is staying with Java 6 for compatibility reasons
3. it required a number of additional jars

For reasons above I do not think it should be part of SJK out of box.

I would suggest to add option alternative to -s which would allow to rewrite whole URI. This would not create any dependency for JBoss stuff and would allow you to use SJK with JBoss by adding additional jars to classpath.

**Comment by kyxap1** [comment]
Hello,

here is a simple jmx protocol overriding
#17

**Comment by aragozin** [comment]
Included into 0.4.2 release
