### ISSUE TITLE
Question about GC CPU Utilization

### ISSUE THREAD

**Issue by stefanodoni** [aragozin/jvm-tools#16]
Hi Alexey,

Many thanks for this great tool!

I have a question. I noticed an interesting metric about GC CPU utilization in the output of the 'ttop' tool:

2016-06-29T15:44:56.789+0200 Process summary 
  process cpu=12.74%
  application cpu=10.03% (user=9.55% sys=0.47%)
  other: cpu=2.71% 
  **GC cpu=0.05% (young=0.05%, old=0.00%)**

Question: is this the actual amount of CPU that is consumed by the JVM GC threads?

If so, I wonder where does it come from. I have seen this metric in GC logs (i.e. Times usr= sys=), is it the same?
Was not aware that it was exposed also via JMX...

**Comment by aragozin** [comment]
Hi,
This is tricky question.
Line you have highlighted is calculated not via JMX, but using so called perf counters (this line is available only for PID based connections).
Though, I have suspicion that these number are not accurate because I'm misinterpreting wallclock time for CPU time (I havn't chance to very that).
In addition, some GC timings are actually available via JMX too. Try out gc command which is fully JMX based.

**Comment by stefanodoni** [comment]
Hi Alex,

Thanks for the quick reply.

I looked into the code and found that the GC CPU Util numbers reported by 'ttop' are extracted here:

    public PerfCounterGcCpuUsageMonitor(long pid) {
        JStatData jd = JStatData.connect(pid);
        gc0 = (TickCounter) jd.getAllCounters().get("sun.gc.collector.0.time");
        gc1 = (TickCounter) jd.getAllCounters().get("sun.gc.collector.1.time");
    }

Unfortunately, such 'sun.*' counters are not documented, and available doc seem to discourage using them.

However, it looks like other java performance tools use them, such as JMH http://java-performance.info/introduction-jmh-profilers/ and https://github.com/rodm/teamcity-jvm-monitor-plugin/blob/master/agent/src/main/java/teamcity/jvm/monitor/agent/monitor/JvmDataCollector.java.

However, looking at these other tools output, it looks like the sun.gc.collector times' are actually GC elapsed times: they are used to calculate GC overhead, as reported in jstat output. They do not seem to count actual GC CPU usage.

If so, ttop output should better reflect the actual semantic.

What's your view on that?

**Comment by aragozin** [comment]
I agree, though before changing code I was planning to investigate "actual
semantic" of these and few other counter.
Specifically how this counters work for concurrent collector. Still haven't
done it unfortunately.

**Comment by aragozin** [comment]
"GC cpu", was changed to "GC time"
