### ISSUE TITLE
What is current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [aragozin/jvm-tools#19]
Is the current stable 0.4.2 or 0.4.3?

I noticed that the link https://bintray.com/artifact/download/aragozin/generic/sjk-plus-0.4.3.jar doesn't exist yet, so the Homebrew formula cannot be upgraded, assuming 0.4.3 is now the current stable.

Thanks!

**Comment by aragozin** [comment]
I have just uploaded 0.4.3 to bintary

**Comment by ilovezfs** [comment]
@aragozin voilà: https://github.com/Homebrew/homebrew-core/pull/4126

Thanks!
