### ISSUE TITLE
Question about users and PID connection

### ISSUE THREAD

**Issue by gquintana** [aragozin/jvm-tools#20]
A given application is running as user *foo* with PID 12345, it puts its metadata in a folder named  `/tmp/hsperfdata_foo` 

By setting the appropriate rights, is it possible for another user *bar* to run `sjk ttop -p 12345`. By default, the tool is looking for metadata in `/tmp/hsperfdata_bar` and doesn't find PID 12345:
```
Failed to access MBean server: 12345
```

**Comment by aragozin** [comment]
If there is a way to do it, I'm not aware of it. 
Setting file permissions is not enough, unix domain socket is used for communication.
I can suggest you to use JMX socket connection instead of PID.
