### ISSUE TITLE
test failures with 0.6

### ISSUE THREAD

**Issue by ilovezfs** [aragozin/jvm-tools#27]
Trying to build 0.6 for Homebrew fails unless I pass `-DskipTests` to maven.

Full build log is here: https://gist.github.com/ilovezfs/ce0fc2ff8ed1e140c97990636a468fad

**Comment by aragozin** [comment]
There some discrepancies in decimal formatting between Java 6 and Java 8. Test were also depending on local time zone.
It is fixed now, though, `-DskipTests` for repackaging release branch is ok IMHO

**Comment by ilovezfs** [comment]
Thanks @aragozin!
