### ISSUE TITLE
feature request: show stacktrace in ttop

### ISSUE THREAD

**Issue by ismlsmile** [aragozin/jvm-tools#30]
Currently only thread name is showed. Could the stackstrace of the thread be showed? Just like the output of jstack.

**Comment by aragozin** [comment]
Printing stack traces would make output long and unusable.

**Comment by ismlsmile** [comment]
What is the correct way to debug cpu problem using ttop? using ttop to get the thread id first and then using jstack to see what code is running?

**Comment by aragozin** [comment]
If you want to get insight about your code behavior, profiler is better tool. SJK has sampling profiler built in. You can capture snapshot with [stcap] command and analyze it with [ssa] command. Snapshot is essentially a number of thread dumps is compressed binary format. With [ssa] you can few types of reports (e.g. flame graphs, method frequency histograms and few others).

 [stcap]: https://github.com/aragozin/jvm-tools/blob/master/sjk-core/COMMANDS.md#stcap-command
 [ssa]: https://github.com/aragozin/jvm-tools/blob/master/sjk-core/COMMANDS.md#ssa-command
