### ISSUE TITLE
ttop not working

### ISSUE THREAD

**Issue by stefan-reich** [aragozin/jvm-tools#39]
What am I doing wrong? This is JDK 10 on Linux. Does the other process need special options?

```
stefan@stefan-quadcore ~/dev/jvm-tools/sjk/target $ java -jar sjk-0.11-SNAPSHOT.jar ttop -p 13491
Restarting java with unlocked package access
Failed to access MBean server: 13491
```

Greetings

**Comment by aragozin** [comment]
Try use jstack or jcmd with same PID. If they work try sjk with -X flag to get stack trace.
