### ISSUE TITLE
can we have something similar to jvmtop?

### ISSUE THREAD

**Issue by kant111** [aragozin/jvm-tools#45]
Can we have something similar to https://github.com/patric-r/jvmtop/blob/master/doc/ConsoleProfiler.md It has been very useful and so simple to use. Quickly shows where the CPU cycles are spent. I tried to replicate the same using `stcap` and `ssa` but I couldn't quite get the output similar to jvmtop?

**Comment by aragozin** [comment]
Below is output of `ssa --histo --by-term -f dump.sjk` command which is IMHO very similar to your example.

    Trc    (%)  Frm N  Term   (%)  Frame
    60007  68%  60007  60007  68%  sun.misc.Unsafe.park(Native Method)
    15207  17%  15207  15207  17%  sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
     6994   8%  6994    6994   8%  java.lang.Thread.sleep(Native Method)
     2184   2%  2184    2184   2%  java.lang.Object.wait(Native Method)
      714   0%  714      714   0%  java.io.FileInputStream.readBytes(Native Method)
      547   0%  547      547   0%  sun.management.ThreadImpl.dumpThreads0(Native Method)
      547   0%  547      547   0%  java.net.DualStackPlainSocketImpl.accept0(Native Method)
      522   0%  522      522   0%  java.lang.String.intern(Native Method)
       45   0%  45        45   0%  java.lang.Class.forName0(Native Method)
       42   0%  42        42   0%  java.util.HashMap.hash(HashMap.java:338)
       39   0%  39        39   0%  java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:9
       37   0%  37        37   0%  sun.nio.ch.SocketDispatcher.write0(Native Method)
       36   0%  36        36   0%  java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:9
       35   0%  35        35   0%  sun.nio.ch.WindowsSelectorImpl.setWakeupSocket0(Native Method)
       33   0%  33        33   0%  java.io.ObjectOutputStream$BlockDataOutputStream.getUTFLength(Objec
       31   0%  31        31   0%  java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:9
       52   0%  52        26   0%  java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:113
       26   0%  26        26   0%  java.io.ObjectOutputStream$BlockDataOutputStream.writeBytes(ObjectO
       24   0%  24        24   0%  java.util.concurrent.ConcurrentHashMap$Traverser.advance(Concurrent
       24   0%  24        24   0%  com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.g
       22   0%  22        22   0%  java.lang.System.identityHashCode(Native Method)

You may argue that histogram includes both CPU spending and idle methods. Which is true. There is no relaible way to distinguish on-CPU from idle frame in thread dump based sampling, though you can explicitly filter frames which is known to be non-CPU operation. Or on can use different sampling tool (out of box sjk can process JFR recordings, `perf` format is on road map).

If there are other key differences, please explain.
