### ISSUE TITLE
Does SSA use asyncgetcalltrace or JVMTI getCallTrace to walkthrough Java stack trace

### ISSUE THREAD

**Issue by sattishv** [aragozin/jvm-tools#55]
Team,

Thanks for creating this project. The tools developed were really useful particularly ssa with flamegraphs. But we would like to know whether ssa uses asyncgetcalltrace(AGCT) or JVMTI getCallTrace to walkthrough Java stack trace. Since AGCT output would be accurate in walking through stack asynchronously not impacted by safepoint bias.

Sattish.

**Comment by aragozin** [comment]
Hi,

`ssa` is using input file. SJK own sampler `stcap` is using a naive thread dump sampling approach.
Though, `ssa` can use Java Flight Recorder files. But please keep in mind that you need `-XX:+DebugNonSafepoint` option enabled for target JVM.

If you are looking for AGCT based profiler take a look at [](https://github.com/jvm-profiling-tools/async-profiler)

I would also recommend you to take a look at my article  on topic of sampling bias
[](https://blog.ragozin.info/2019/03/lies-darn-lies-and-sampling-bias.html)

**Comment by sattishv** [comment]
Hi,

Thanks a lot for elucidating the queries raised.Appreciate your thought on thread dump sampling
