### ISSUE TITLE
Ttop with java7: IllegalArgumentException: Comparison method violates its general contract

### ISSUE THREAD

**Issue by alexbudarov** [aragozin/jvm-tools#6]
Hi,

I've used latest binary build (2014-09-06).
Got a "comparator violates its general contract method" error with java 1.7.0_51.

--
xxxx@yyyy:~/files/sjk$ java -jar sjk.jar ttop -p 4523 -n 20 -o CPU
>/home/xxxx/files/sjk/sjk.jar
Monitoring threads ...

Unexpected error: java.lang.IllegalArgumentException: Comparison method violates its general contract!

--

When relaunched with -Djava.util.Arrays.useLegacyMergeSort=true system property - it worked fine.

P.S. Thanks for sharing your production tools with community!

**Comment by aragozin** [comment]
There were a bug in CPU time comparator indeed, but it should have been fixed earlier.
Anyway if have uploaded newer version.
