### ISSUE TITLE
jackson->minimal-json for mxdump?

### ISSUE THREAD

**Issue by pcarrier** [aragozin/jvm-tools#8]
Jackson is a big dependency  (relatively to other components).

`WriterConfig.PRETTY_PRINT` from https://github.com/ralfstx/minimal-json offers similar functionality for a tenth of the size.

**Comment by aragozin** [comment]
I agree. But I don't really use mxdump myself, it was pulled in with some
other contribution.
If you care to submit a patch, I will gladly merge it.
